Don't override user provided compile definitions
ros2/rosidl_typesupport pull request #145
Opened 2023-06-06 00:11 UTC by emersonknapp

Part of ros2/rosidl#743

The `rosidl_typesupport_cpp` C++ target was overriding user provided compiler options, which hid (for example) `-Wdeprecated` warnings in generated code in `nav2_msgs`

2023-06-06 11:05 UTC, clalancette requested changes

2023-06-06 11:05 UTC, clalancette commented on rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
>      CXX_STANDARD 14)
```suggestion
    CXX_STANDARD 17)
```

(I know this isn't the goal of this PR, but to make it consistent with https://github.com/ros2/rosidl/pull/750 I think we should do this)

2023-06-06 15:28 UTC, emersonknapp commented
Gist: https://gist.githubusercontent.com/emersonknapp/c6789af2426c339278a67550f46ca634/raw/181d85f1ca93d4cbf3472e6379a59ffdbd47a395/ros2.repos
BUILD args: 
TEST args: 
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/12163
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18861)](http://ci.ros2.org/job/ci_linux/18861/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13399)](http://ci.ros2.org/job/ci_linux-aarch64/13399/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19614)](http://ci.ros2.org/job/ci_windows/19614/)

2023-06-06 15:51 UTC, clalancette commented on rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake
>      CXX_STANDARD 14)
Ah, interesting.  OK, at least it will be consistent then.

2023-06-06 15:51 UTC, clalancette approved these changes

2023-06-06 21:41 UTC, emersonknapp commented
Rerunning aarch64 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13403)](https://ci.ros2.org/job/ci_linux-aarch64/13403/)

2023-06-07 12:49 UTC, merged

2023-06-08 16:24 UTC, quarkytale commented
@Mergifyio backport iron humble